CREATE TABLE CALENDAR_USERS (
    ID INT IDENTITY,
    EMAIL VARCHAR(256) NOT NULL UNIQUE,
    PASSWORD VARCHAR(256) NOT NULL,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL
);

CREATE TABLE EVENTS (
    ID INT IDENTITY,
    STARTS_AT TIMESTAMP NOT NULL,
    ENDS_AT TIMESTAMP NULL,
    SUMMARY VARCHAR(256) not null,
    DESCRIPTION VARCHAR(500) not null,
    OWNER_ID INT NOT NULL,
    ATTENDEE_ID INT NOT NULL,
    FOREIGN KEY(OWNER_ID) REFERENCES CALENDAR_USERS(ID),
    FOREIGN KEY(ATTENDEE_ID) REFERENCES CALENDAR_USERS(ID)
);
