<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:risk-analyzer="http://scirisk.com/xml/ns/risk-analyzer"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://scirisk.com/service/risk-analyzer"
    targetNamespace="http://scirisk.com/service/risk-analyzer">

  <wsdl:types>
    <xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns:risk-analyzer="http://scirisk.com/xml/ns/risk-analyzer">
      <xsd:import namespace="http://scirisk.com/xml/ns/risk-analyzer" schemaLocation="risk-analyzer_1_0.xsd" />
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="CalculateRequest">
    <wsdl:part element="risk-analyzer:CalculateRequest" name="CalculateRequest" />
  </wsdl:message>

  <wsdl:message name="CalculateResponse">
    <wsdl:part element="risk-analyzer:CalculateResponse" name="CalculateResponse" />
  </wsdl:message>

  <wsdl:portType name="RiskAnalyzer">
    <wsdl:operation name="Calculate">
      <wsdl:input message="tns:CalculateRequest" name="CalculateRequest" />
      <wsdl:output message="tns:CalculateResponse" name="CalculateResponse" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="RiskAnalyzerSoap11" type="tns:RiskAnalyzer">
    <soap:binding style="document"  transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Calculate">
      <wsdl:input name="CalculateRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="CalculateResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="RiskAnalyzerService">
    <wsdl:port binding="tns:RiskAnalyzerSoap11" name="RiskAnalyzerSoap11">
      <soap:address location="http://localhost:8080/soap/endpoint/" />
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
